version: "3"

services:
  calculator:
    image: springbootdocker
    build:
      context: ./
      # path dockerfile
      dockerfile: SpringDockerfile
    volumes:
      - ./test-refinitive-calculator:/home/app/src
    # - /test-refinitive-calculator:/data/test-refinitive-calculator
    ports:
      # exposed port 8080 on the container to port 8081 on the host machine.
      - "8081:8080"

  front-react:
    image: reactdocker
    depends_on:
      - calculator
    build:
      context: ./
      dockerfile: ReactDockerfile
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    stdin_open: true

    ports:
      - "3001:3000"
