version: "3"

services:
  calculator-01:
    image: calculator:0.1
    build:
      context: ./
      # path dockerfile
      dockerfile: /SpringDockerfile
    volumes:
      - /test-refinitive-calculator:/data/test-refinitive-calculator
    ports:
      # exposed port 8080 on the container to port 8081 on the host machine.
      - "8081:8080"
